### ISSUE TITLE
How to track items in a room?

### ISSUE THREAD

**Issue by ericclack** [ericclack/python-text-adventure#1]
If a room has a torch and the player takes it, the room should no longer have the torch. 

We can use function attributes, like this: 
https://github.com/ericclack/python-text-adventure/blob/main/adventureN.py#L40

Seems like a good solution?

**Comment by andyborrell** [comment]
That's a pretty good solution.  The downside is it's very Python-specific. 
I think I'd still be tempted to do something more like:

```
class Room:
    def __init__(self):
        self.items=[]

...

entrance_room = Room()
def entrance:
    ...
    entrance_room.items.remove('torch')
    ... 
```

It's a bit more code, but it might be confusing to introduce idea of function attributes before class attributes.  We wouldn't want ninjas to think functions are where attributes normally live.

**Comment by ericclack** [comment]
That works and is certainly less python specific. Having done this, I can't resist adding the directions to the room too:
https://github.com/ericclack/python-text-adventure/blob/main/adventureN.py
